#!/usr/bin/env python3
"""Slim the course notebooks by removing their stored outputs.

The figures, animations and audio in these notes are all generated by the notebooks themselves, so nothing is lost:
open a cleaned notebook and run it (Run > Run All Cells) to regenerate every output. Cleaning keeps the repository small
(animations are stored as embedded images and can take several MB each).

Usage
    python clean_notebooks.py                      # clean every notebook in this folder
    python clean_notebooks.py 05_*.ipynb           # clean selected notebooks
    python clean_notebooks.py --keep-small 200     # keep outputs smaller than 200 kB (e.g. static figures)
    python clean_notebooks.py --check              # report sizes only; change nothing (exit code 1 if any output is stored)

Only the standard library is needed.
"""
import argparse
import glob
import json
import os
import sys


def output_size(out):
    return len(json.dumps(out))


def clean(path, keep_kb=None, check=False):
    with open(path, encoding='utf-8') as fh:
        nb = json.load(fh)
    before = os.path.getsize(path)
    n_out = 0
    for cell in nb.get('cells', []):
        if cell.get('cell_type') != 'code':
            continue
        outs = cell.get('outputs', [])
        n_out += len(outs)
        if not check:
            if keep_kb is None:
                cell['outputs'] = []
            else:
                cell['outputs'] = [o for o in outs if output_size(o) < keep_kb * 1000]
            cell['execution_count'] = None
            cell.get('metadata', {}).pop('execution', None)
    if check:
        return before, before, n_out
    for key in ('widgets', 'signature'):
        nb.get('metadata', {}).pop(key, None)
    with open(path, 'w', encoding='utf-8') as fh:
        json.dump(nb, fh, indent=1, ensure_ascii=False)
        fh.write('\n')
    return before, os.path.getsize(path), n_out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('notebooks', nargs='*', help='notebooks to clean (default: all *.ipynb in this folder)')
    ap.add_argument('--keep-small', type=float, metavar='KB', help='keep individual outputs smaller than KB kilobytes')
    ap.add_argument('--check', action='store_true', help='report only; exit 1 if any notebook stores outputs')
    a = ap.parse_args()
    here = os.path.dirname(os.path.abspath(__file__))
    paths = a.notebooks or sorted(glob.glob(os.path.join(here, '*.ipynb')))
    dirty = 0
    for p in paths:
        b, after, n = clean(p, a.keep_small, a.check)
        dirty += n > 0
        if a.check:
            print(f'{os.path.basename(p):50s} {b/1e6:6.2f} MB  {n:3d} stored outputs')
        else:
            print(f'{os.path.basename(p):50s} {b/1e6:6.2f} MB -> {after/1e6:6.2f} MB')
    if a.check and dirty:
        sys.exit(1)


if __name__ == '__main__':
    main()
